### ISSUE TITLE
No rule to make target selftest-tiny, needed by selftest.

### ISSUE THREAD

**Issue by zeim839** [rofirrim/gcc-tiny#1]
Problem: `make[3]: *** No rule to make target selftest-tiny, needed by selftest.`
The latest version of GCC requires a `selftest` target in Make-lang.in

Solution: (in tiny/Make-lang.in):
```Makefile
selftest-tiny:
```
Add a blank `selftest-tiny` line. 

See also: [GCC Go compiler self-test](https://github.com/gcc-mirror/gcc/blob/master/gcc/go/Make-lang.in#L147)

**Comment by HSorensen** [comment]
This introduction to GCC frontend development really motivated me to restart my own frontend project. I am using the latest GCC version with Tiny as a base, so a few changes were needed, check it out:
[GNU PL/I Tiny](https://github.com/HSorensen/gccpl1/tree/tiny-source/src-gcc-tiny)

**Comment by zeim839** [comment]
@HSorensen Thank you for your response, I'm likewise working on a frontend project and being able to reference a minimal language like Tiny has been incredibly useful. GCC's documentation (or lack thereof) has been an enormous nuisance. 

I've managed to get the build process working, but ill definitely be looking through your repository for more help.

Perhaps you should contact roffirim and help write up an updated version of the tutorial.

**Comment by HSorensen** [comment]
@rofirrim Would you be interested in bringing Tiny to the latest version of GCC?
Perhaps continue the writeup on ThinkInGeek with some additional chapters.
Some ideas I would like to help with:

- Tiny for GCC 14
- Adding CLI options to your front end
- Integrating with GCC make system
- Essential Language Hooks
- Enable GDB for source level debugging 
- Creating shared objects
- Adding frontend documentation
- Adding test cases
- Interlanguage considerations

**Comment by SamuraiCrow** [comment]
@HSorensen 
I guess you could just fork it and write a follow up article series on your blogging platform of choice just linking to the originals.  Otherwise, the proper etiquette for GitHub is a pull request with the changes needed.

**Comment by zeim839** [comment]
> Otherwise, the proper etiquette for GitHub is a pull request with the changes needed.

I disagree, it's commonplace to discuss major changes in issues and I don't see why the original author shouldn't be engaged in updating documentation blog posts. Granted, it's probably best if this discussion was moved to its own separate issue. 

Let me know what you think.

**Comment by rofirrim** [comment]
Hi all,

Thank you for your interest on gcc-tiny and I'm happy to learn that it has been useful and motivating.

However, I never planned to make it a complete front-end with a bunch of features. Instead the goal was to build the minimum that (I thought) was illustrative of a front-end for GCC. It is not in my plans to develop it further at this moment.

If you'd like to extend gcc-tiny, I encourage you to fork it.

**Comment by SamuraiCrow** [comment]
The code is GPL2 so the right to fork and update is already implied as long as it is not relicensed by the original author.  Articles can even be hosted on GitHub itself using GitHub Pages.  Only duplicating the articles themselves needs additional permission.

**Comment by rofirrim** [comment]
> I understand if you have moved on to other projects but I wanted to ask: @SamuraiCrow and myself have started, well SC really started the [gcc-tiny](https://github.com/GCC-Tiny) github organization, would you like to join?

Thanks for the invitation, @HSorensen. I am afraid I will have to decline because I won't be able to contribute time to the project.

> Would you be able to contribute the source for the blog posts, or give us permission to copy them ?

Feel free to copy them, retain some basic attribution and that will do.

> thanks for all your work on the Tiny blogs and source

You're welcome. I'm glad they inspired you.
